// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProduccionApp.Data;

#nullable disable

namespace ProduccionApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProduccionApp.Models.OrdenProceso", b =>
                {
                    b.Property<int>("OrdenProcesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcesoFabricacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Secuencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenProcesoId");

                    b.HasIndex("ProcesoFabricacionId");

                    b.HasIndex("OrdenProduccionId", "ProcesoFabricacionId")
                        .IsUnique();

                    b.ToTable("OrdenProcesos");
                });

            modelBuilder.Entity("ProduccionApp.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("OrdenProduccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAProducir")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEntregaEstimada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("OrdenProduccionId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("OrdenesProduccion");
                });

            modelBuilder.Entity("ProduccionApp.Models.ProcesoFabricacion", b =>
                {
                    b.Property<int>("ProcesoFabricacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionEstimadaHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("ProcesoFabricacionId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ProcesosFabricacion");

                    b.HasData(
                        new
                        {
                            ProcesoFabricacionId = 1,
                            Descripcion = "Corte de piezas de cuero y materiales según molde.",
                            DuracionEstimadaHoras = 4,
                            Nombre = "Corte"
                        },
                        new
                        {
                            ProcesoFabricacionId = 2,
                            Descripcion = "Unión de piezas cortadas mediante costura.",
                            DuracionEstimadaHoras = 6,
                            Nombre = "Costura"
                        },
                        new
                        {
                            ProcesoFabricacionId = 3,
                            Descripcion = "Ensamblaje de la suela con el corte cosido.",
                            DuracionEstimadaHoras = 5,
                            Nombre = "Ensamblado"
                        },
                        new
                        {
                            ProcesoFabricacionId = 4,
                            Descripcion = "Inspección final de defectos y acabados.",
                            DuracionEstimadaHoras = 2,
                            Nombre = "Control de Calidad"
                        },
                        new
                        {
                            ProcesoFabricacionId = 5,
                            Descripcion = "Empaque final del producto para distribución.",
                            DuracionEstimadaHoras = 1,
                            Nombre = "Empaque"
                        });
                });

            modelBuilder.Entity("ProduccionApp.Models.OrdenProceso", b =>
                {
                    b.HasOne("ProduccionApp.Models.OrdenProduccion", "OrdenProduccion")
                        .WithMany("OrdenProcesos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProduccionApp.Models.ProcesoFabricacion", "ProcesoFabricacion")
                        .WithMany("OrdenProcesos")
                        .HasForeignKey("ProcesoFabricacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenProduccion");

                    b.Navigation("ProcesoFabricacion");
                });

            modelBuilder.Entity("ProduccionApp.Models.OrdenProduccion", b =>
                {
                    b.Navigation("OrdenProcesos");
                });

            modelBuilder.Entity("ProduccionApp.Models.ProcesoFabricacion", b =>
                {
                    b.Navigation("OrdenProcesos");
                });
#pragma warning restore 612, 618
        }
    }
}
