// <auto-generated />
using System;
using Administraar_empresacdec_Calzado_Innovador_S.A_.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Administraar_empresacdec_Calzado_Innovador_S.A_.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.OrdenProceso", b =>
                {
                    b.Property<int>("OrdenProduccionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcesoFabricacionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("TEXT");

                    b.Property<int>("Secuencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenProduccionId", "ProcesoFabricacionId");

                    b.HasIndex("ProcesoFabricacionId");

                    b.ToTable("OrdenProcesos");
                });

            modelBuilder.Entity("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAProducir")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEntregaEstimada")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.ToTable("OrdenesProduccion");
                });

            modelBuilder.Entity("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.ProcesoFabricacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionEstimadaHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ProcesosFabricacion");
                });

            modelBuilder.Entity("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.OrdenProceso", b =>
                {
                    b.HasOne("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.OrdenProduccion", "OrdenProduccion")
                        .WithMany("OrdenProcesos")
                        .HasForeignKey("OrdenProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.ProcesoFabricacion", "ProcesoFabricacion")
                        .WithMany("OrdenProcesos")
                        .HasForeignKey("ProcesoFabricacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenProduccion");

                    b.Navigation("ProcesoFabricacion");
                });

            modelBuilder.Entity("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.OrdenProduccion", b =>
                {
                    b.Navigation("OrdenProcesos");
                });

            modelBuilder.Entity("Administraar_empresacdec_Calzado_Innovador_S.A_.Models.ProcesoFabricacion", b =>
                {
                    b.Navigation("OrdenProcesos");
                });
#pragma warning restore 612, 618
        }
    }
}
